"""Vision-tool cards - what a tool is, and exactly how to call it.

Returned by the :class:`pictograph.resources.tools.Tools` resource. A *vision tool*
is anything in your organization that takes an image (or a video, or a dataset) and
returns predictions: **SAM3** (built in), each ready **model**, each active
**deployment**, and each **workflow**.

A :class:`ToolCard` is generated by the platform from what it stores about that tool -
never hand-written - and answers, in one object: what it is, which inputs each way of
running it accepts, its parameters, the shape of what it returns, the exact CLI /
Python / HTTP call, and what each costs. The intended habit for an agent is
*list, describe, then run*.

Response-side schema (``extra="ignore"``): the platform adds facts to a card over
time, and an older SDK keeps reading the ones it knows.
"""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field

ToolKind = Literal["sam3", "model", "deployment", "workflow"]

_MICRO_USD_PER_USD = 1_000_000


class _Tool(BaseModel):
    model_config = ConfigDict(extra="ignore", populate_by_name=True)


class ToolSummary(_Tool):
    """One row of ``client.tools.list()``.

    ``tool`` is the handle to pass to ``client.tools.describe`` (and to
    ``pictograph tools describe``): ``"sam3"``, ``"model/<name>"``,
    ``"deployment/<name>"`` or ``"workflow/<name>"``.
    """

    tool: str
    kind: str
    id: str | None = None
    name: str
    task: str | None = None
    status: str | None = None
    summary: str = ""


class ToolInput(_Tool):
    """Whether one way of running a tool accepts one kind of input.

    ``kind`` is ``file``, ``url``, ``bytes``, ``video`` or ``dataset``. When
    ``supported`` is false, ``note`` says what to do instead.
    """

    kind: str
    supported: bool = False
    note: str | None = None


class ToolCost(_Tool):
    """What one way of running a tool costs.

    ``micro_usd`` is the price in micro-USD (``1 USD = 1_000_000``) for one ``per``
    (``image``, ``frame`` or ``minute``); ``0`` means free and ``None`` means it
    depends (read ``summary``). ``estimate`` marks a price that is settled from
    what the run actually measured.
    """

    summary: str = ""
    micro_usd: int | None = None
    per: str | None = None
    estimate: bool = False
    options: list[dict[str, Any]] = Field(default_factory=list)

    @property
    def usd(self) -> float | None:
        """``micro_usd`` in dollars, or ``None`` when the price depends."""
        return None if self.micro_usd is None else self.micro_usd / _MICRO_USD_PER_USD

    @property
    def free(self) -> bool:
        return self.micro_usd == 0


class ToolRun(_Tool):
    """The exact call for one way of running a tool, in each interface that has one."""

    cli: str | None = None
    python: str | None = None
    http: str | None = None


class ToolMode(_Tool):
    """One way of running a tool (``hosted``, ``local``, ``endpoint``, ``file``, ...)."""

    mode: str
    title: str = ""
    description: str = ""
    inputs: list[ToolInput] = Field(default_factory=list)
    limits: dict[str, Any] = Field(default_factory=dict)
    requires: list[str] = Field(default_factory=list)
    # ``False`` when the call changes nothing, else a sentence saying what it writes.
    writes: bool | str = False
    cost: ToolCost = Field(default_factory=ToolCost)
    returns: str | None = None
    run: ToolRun = Field(default_factory=ToolRun)

    def accepts(self, kind: str) -> bool:
        """Whether this mode takes ``kind`` (``file`` / ``url`` / ``bytes`` / ``video`` / ``dataset``)."""
        return any(i.kind == kind and i.supported for i in self.inputs)


class ToolParameter(_Tool):
    """A parameter a tool takes, with the bounds the API enforces."""

    name: str
    type: str = "string"
    default: Any = None
    minimum: float | None = None
    maximum: float | None = None
    choices: list[str] = Field(default_factory=list)
    applies_to: list[str] = Field(default_factory=list)
    description: str = ""


class ToolClass(_Tool):
    """A class a tool predicts, and the annotation type it comes back as."""

    name: str
    type: str | None = None


class ToolOutput(_Tool):
    """The shape of ONE prediction: prose, its JSON Schema, and an example."""

    type: str | None = None
    description: str = ""
    coordinates: str | None = None
    # `schema` on the wire; named apart from pydantic's own `BaseModel.schema`.
    json_schema: dict[str, Any] | None = Field(default=None, alias="schema")
    example: dict[str, Any] | None = None


class ToolRelated(_Tool):
    """Another tool tied to this one (a model's endpoint, a workflow's models)."""

    tool: str
    relation: str = ""


class ToolCard(ToolSummary):
    """Everything an agent needs to call one vision tool."""

    about: str | None = None
    classes: list[ToolClass] = Field(default_factory=list)
    facts: dict[str, Any] = Field(default_factory=dict)
    parameters: list[ToolParameter] = Field(default_factory=list)
    output: ToolOutput | None = None
    modes: list[ToolMode] = Field(default_factory=list)
    related: list[ToolRelated] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)

    def mode(self, name: str) -> ToolMode | None:
        """The mode called ``name``, or ``None`` when this tool has no such way to run."""
        return next((m for m in self.modes if m.mode == name), None)

    def to_markdown(self) -> str:
        """The card as Markdown - what ``pictograph tools describe`` prints."""
        out: list[str] = [f"# {self.name}", "", f"`{self.tool}` · {self.kind}"]
        if self.task and self.task != self.kind:
            out[-1] += f" · {self.task.replace('_', ' ')}"
        if self.status:
            out[-1] += f" · {self.status}"
        out += ["", self.summary]
        if self.about and self.about != self.summary:
            out += ["", self.about]
        if self.classes:
            shown = ", ".join(c.name for c in self.classes[:40])
            more = f", and {len(self.classes) - 40} more" if len(self.classes) > 40 else ""
            kind = f" ({self.classes[0].type})" if self.classes[0].type else ""
            out += ["", f"**Classes{kind}:** {shown}{more}"]
        facts = [(k, v) for k, v in self.facts.items() if v not in (None, "", [], {}, False)]
        if facts:
            out += ["", "## Facts", ""]
            for k, v in facts:
                label = k.replace("_", " ")
                if isinstance(v, list) and v and all(isinstance(item, dict) for item in v):
                    # A list of things (a workflow's models, its measures): one each.
                    out.append(f"- {label}:")
                    out += [f"  - {_item(item)}" for item in v]
                else:
                    out.append(f"- {label}: {_fact(v)}")
        if self.parameters:
            out += ["", "## Parameters", ""]
            for p in self.parameters:
                bits = [p.type]
                if p.default is not None:
                    bits.append(f"default {p.default}")
                if p.minimum is not None and p.maximum is not None:
                    bits.append(f"{_num(p.minimum)}-{_num(p.maximum)}")
                if p.choices:
                    bits.append(" | ".join(p.choices))
                where = f" [{', '.join(p.applies_to)}]" if p.applies_to else ""
                out.append(f"- `{p.name}` ({', '.join(bits)}){where}: {p.description}")
        if self.output:
            out += ["", "## Output", "", self.output.description]
            if self.output.coordinates:
                out += ["", f"Coordinates: {self.output.coordinates}"]
            if self.output.example:
                import json

                out += ["", "```json", json.dumps(self.output.example, indent=2), "```"]
        for m in self.modes:
            out += ["", f"## {m.title or m.mode} (`{m.mode}`)", "", m.description]
            takes = [i.kind for i in m.inputs if i.supported]
            if takes:
                out += ["", f"Takes: {', '.join(takes)}."]
            for i in m.inputs:
                if i.note and (
                    i.supported or i.kind in ("url", "bytes", "video", "dataset", "file")
                ):
                    out.append(f"- {i.kind}: {'yes' if i.supported else 'no'} - {i.note}")
            if m.requires:
                out += ["", "Needs:"]
                out += [f"- {need}" for need in m.requires]
            if m.limits.get("note"):
                out += ["", f"Limits: {m.limits['note']}"]
            out += [
                "",
                f"Writes: {m.writes if isinstance(m.writes, str) else ('yes' if m.writes else 'nothing')}",
            ]
            out += [f"Cost: {m.cost.summary}"]
            if m.returns:
                out += [f"Returns: {m.returns}"]
            for label, lang, code in (
                ("CLI", "bash", m.run.cli),
                ("Python", "python", m.run.python),
                ("HTTP", "bash", m.run.http),
            ):
                if code:
                    out += ["", f"{label}:", "", f"```{lang}", code, "```"]
        if self.related:
            out += ["", "## Related tools", ""]
            out += [f"- `{r.tool}`: {r.relation}" for r in self.related]
        if self.notes:
            out += ["", "## Notes", ""]
            out += [f"- {n}" for n in self.notes]
        return "\n".join(out) + "\n"


def _num(value: float) -> str:
    return str(int(value)) if float(value).is_integer() else str(value)


def _item(item: dict[str, Any]) -> str:
    """One entry of a list fact: its name, then whatever else it carries."""
    rest = ", ".join(
        f"{k.replace('_', ' ')} {_fact(v)}"
        for k, v in item.items()
        if k != "name" and v not in (None, "", [], {})
    )
    name = item.get("name")
    if not name:
        return rest
    return f"{name} ({rest})" if rest else str(name)


def _fact(value: Any) -> str:
    if isinstance(value, dict) and set(value) == {"metric", "value"}:
        # A score: {"metric": "mAP", "value": 0.61} reads "61.0% mAP".
        score = value["value"]
        if isinstance(score, (int, float)) and 0 <= score <= 1:
            return f"{score * 100:.1f}% {value['metric']}"
        return f"{score} {value['metric']}"
    if isinstance(value, dict):
        return ", ".join(f"{k} {_fact(v)}" for k, v in value.items() if v not in (None, "", [], {}))
    if isinstance(value, list):
        return ", ".join(_fact(v) for v in value) if value else "-"
    if isinstance(value, bool):
        return "yes" if value else "no"
    return str(value)


__all__ = [
    "ToolCard",
    "ToolClass",
    "ToolCost",
    "ToolInput",
    "ToolKind",
    "ToolMode",
    "ToolOutput",
    "ToolParameter",
    "ToolRelated",
    "ToolRun",
    "ToolSummary",
]
