"""Tools resource - the vision tools your organization can call, and how to call each.

A *vision tool* is anything here that takes an image (or a video, or a dataset) and
returns predictions: **SAM3** (built in, no training), each ready **model**, each
active **deployment**, and each **workflow**. This resource is how an agent finds out
what exists and how to use it, instead of reading documentation written for people::

    for tool in client.tools.list():
        print(tool.tool, "-", tool.summary)

    card = client.tools.describe("model/Shelf Detector")
    print(card.mode("hosted").run.python)  # the exact call, ready to run

A card is generated by the platform from what it stores about the tool, so it cannot
go stale: its classes, its parameters with the bounds the API enforces, the shape of
one prediction, which inputs each way of running it accepts (file, URL, bytes, video,
dataset), the exact CLI / Python / HTTP call, and what each costs.

Not to be confused with :mod:`pictograph.agents`, which hands the SDK's own platform
operations to an agent framework as tool definitions. These are YOUR vision tools.
"""

from __future__ import annotations

from typing import Any
from urllib.parse import quote

from pictograph.models.tool import ToolCard, ToolKind, ToolSummary
from pictograph.resources._base import Resource

_API_PATH = "/api/v1/developer/tools/vision"
_PAGE = 500
_NAMED_KINDS = ("model", "deployment", "workflow")


def card_path(tool: str) -> str:
    """The card route for a tool handle (``sam3``, ``model/<name>``, ...).

    Shared by the sync and async resources so both read a handle the same way.
    """
    handle = tool.strip()
    if handle == "sam3":
        return f"{_API_PATH}/sam3"
    kind, sep, ref = handle.partition("/")
    if not sep or kind not in _NAMED_KINDS or not ref.strip():
        raise ValueError(
            f"Not a tool: {tool!r}. A tool is 'sam3', 'model/<name>', "
            "'deployment/<name>' or 'workflow/<name>' - the `tool` value of a row "
            "from client.tools.list()."
        )
    return f"{_API_PATH}/{kind}/{quote(ref.strip(), safe='')}"


def list_params(kind: str | None, offset: int) -> dict[str, Any]:
    params: dict[str, Any] = {"limit": _PAGE, "offset": offset}
    if kind is not None:
        params["kind"] = kind
    return params


class Tools(Resource):
    """List the organization's vision tools and read the card that says how to call one."""

    def list(self, *, kind: ToolKind | None = None) -> list[ToolSummary]:
        """Every vision tool this organization can call right now.

        SAM3 first (it is always there), then ready models (newest first), active
        deployments, and workflows.

        Args:
            kind: Only tools of this kind - ``"sam3"``, ``"model"``,
                ``"deployment"`` or ``"workflow"``.

        Returns:
            One :class:`~pictograph.models.tool.ToolSummary` per tool. Pass its
            ``tool`` to :meth:`describe`.
        """
        rows: list[ToolSummary] = []
        while True:
            response = self._transport.request(
                "GET", f"{_API_PATH}/", params=list_params(kind, len(rows))
            )
            rows.extend(self._parse_list(ToolSummary, response.get("data", [])))
            if not response.get("pagination", {}).get("has_more") or not response.get("data"):
                return rows

    def describe(self, tool: str) -> ToolCard:
        """One tool's card: what it is and exactly how to call it.

        Args:
            tool: The tool's handle - ``"sam3"``, ``"model/<name>"``,
                ``"deployment/<name>"`` or ``"workflow/<name>"`` (the ``tool`` of a
                :meth:`list` row). A UUID works in place of a name.

        Returns:
            A :class:`~pictograph.models.tool.ToolCard`. ``card.modes`` holds each way
            of running it (``card.mode("hosted")``, ``"local"``, ...) with the inputs
            it accepts, its cost, and the CLI / Python / HTTP call; ``card.parameters``
            and ``card.output`` describe what goes in and what comes back;
            ``card.to_markdown()`` renders it for a person.

        Raises:
            ValueError: ``tool`` is not a tool handle.
            NotFoundError: No such tool in your organization.
            ConflictError: The model exists but is not ready yet.
        """
        response = self._transport.request("GET", card_path(tool))
        return self._parse(ToolCard, response["data"])
